import React from "react";
import { useTranslation } from "next-i18next";
import { HStack, Link } from "@chakra-ui/react";

import DividerIcon from "./icons/DividerIcon";

const LiveBanner = () => {
  const { t } = useTranslation();

  return (
    <HStack
      fontSize="28px"
      whiteSpace="nowrap"
      spacing="3"
      float="right"
      color="#83FFCB"
      my={["10", null, "16"]}
      className="translate-carousel"
      divider={<DividerIcon border="0" />}
    >
      <Link
        href="https://lockdrop.astroport.fi/"
        textTransform="uppercase"
        isExternal
      >
        {t("livebanner-title")}
      </Link>
      <Link
        href="https://lockdrop.astroport.fi/"
        textTransform="uppercase"
        isExternal
      >
        {t("livebanner-title")}
      </Link>
      <Link
        href="https://lockdrop.astroport.fi/"
        textTransform="uppercase"
        isExternal
      >
        {t("livebanner-title")}
      </Link>
      <Link
        href="https://lockdrop.astroport.fi/"
        textTransform="uppercase"
        isExternal
      >
        {t("livebanner-title")}
      </Link>
      <Link
        href="https://lockdrop.astroport.fi/"
        textTransform="uppercase"
        isExternal
      >
        {t("livebanner-title")}
      </Link>
      <Link
        href="https://lockdrop.astroport.fi/"
        textTransform="uppercase"
        isExternal
      >
        {t("livebanner-title")}
      </Link>
      <Link
        href="https://lockdrop.astroport.fi/"
        textTransform="uppercase"
        isExternal
      >
        {t("livebanner-title")}
      </Link>
      <Link
        href="https://lockdrop.astroport.fi/"
        textTransform="uppercase"
        isExternal
      >
        {t("livebanner-title")}
      </Link>
      <Link
        href="https://lockdrop.astroport.fi/"
        textTransform="uppercase"
        isExternal
      >
        {t("livebanner-title")}
      </Link>
      <Link
        href="https://lockdrop.astroport.fi/"
        textTransform="uppercase"
        isExternal
      >
        {t("livebanner-title")}
      </Link>
      <Link
        href="https://lockdrop.astroport.fi/"
        textTransform="uppercase"
        isExternal
      >
        {t("livebanner-title")}
      </Link>
      <Link
        href="https://lockdrop.astroport.fi/"
        textTransform="uppercase"
        isExternal
      >
        {t("livebanner-title")}
      </Link>
      <Link
        href="https://lockdrop.astroport.fi/"
        textTransform="uppercase"
        isExternal
      >
        {t("livebanner-title")}
      </Link>
      <Link
        href="https://lockdrop.astroport.fi/"
        textTransform="uppercase"
        isExternal
      >
        {t("livebanner-title")}
      </Link>
      <Link
        href="https://lockdrop.astroport.fi/"
        textTransform="uppercase"
        isExternal
      >
        {t("livebanner-title")}
      </Link>
      <Link
        href="https://lockdrop.astroport.fi/"
        textTransform="uppercase"
        isExternal
      >
        {t("livebanner-title")}
      </Link>
      <Link
        href="https://lockdrop.astroport.fi/"
        textTransform="uppercase"
        isExternal
      >
        {t("livebanner-title")}
      </Link>
      <Link
        href="https://lockdrop.astroport.fi/"
        textTransform="uppercase"
        isExternal
      >
        {t("livebanner-title")}
      </Link>
      <Link
        href="https://lockdrop.astroport.fi/"
        textTransform="uppercase"
        isExternal
      >
        {t("livebanner-title")}
      </Link>
      <Link
        href="https://lockdrop.astroport.fi/"
        textTransform="uppercase"
        isExternal
      >
        {t("livebanner-title")}
      </Link>
      <Link
        href="https://lockdrop.astroport.fi/"
        textTransform="uppercase"
        isExternal
      >
        {t("livebanner-title")}
      </Link>
      <Link
        href="https://lockdrop.astroport.fi/"
        textTransform="uppercase"
        isExternal
      >
        {t("livebanner-title")}
      </Link>
      <Link
        href="https://lockdrop.astroport.fi/"
        textTransform="uppercase"
        isExternal
      >
        {t("livebanner-title")}
      </Link>
      <Link
        href="https://lockdrop.astroport.fi/"
        textTransform="uppercase"
        isExternal
      >
        {t("livebanner-title")}
      </Link>
      <Link
        href="https://lockdrop.astroport.fi/"
        textTransform="uppercase"
        isExternal
      >
        {t("livebanner-title")}
      </Link>
      <Link
        href="https://lockdrop.astroport.fi/"
        textTransform="uppercase"
        isExternal
      >
        {t("livebanner-title")}
      </Link>
      <Link
        href="https://lockdrop.astroport.fi/"
        textTransform="uppercase"
        isExternal
      >
        {t("livebanner-title")}
      </Link>
      <Link
        href="https://lockdrop.astroport.fi/"
        textTransform="uppercase"
        isExternal
      >
        {t("livebanner-title")}
      </Link>
      <Link
        href="https://lockdrop.astroport.fi/"
        textTransform="uppercase"
        isExternal
      >
        {t("livebanner-title")}
      </Link>
      <Link
        href="https://lockdrop.astroport.fi/"
        textTransform="uppercase"
        isExternal
      >
        {t("livebanner-title")}
      </Link>
      <Link
        href="https://lockdrop.astroport.fi/"
        textTransform="uppercase"
        isExternal
      >
        {t("livebanner-title")}
      </Link>
      <Link
        href="https://lockdrop.astroport.fi/"
        textTransform="uppercase"
        isExternal
      >
        {t("livebanner-title")}
      </Link>
      <Link
        href="https://lockdrop.astroport.fi/"
        textTransform="uppercase"
        isExternal
      >
        {t("livebanner-title")}
      </Link>
      <Link
        href="https://lockdrop.astroport.fi/"
        textTransform="uppercase"
        isExternal
      >
        {t("livebanner-title")}
      </Link>
      <Link
        href="https://lockdrop.astroport.fi/"
        textTransform="uppercase"
        isExternal
      >
        {t("livebanner-title")}
      </Link>
      <Link
        href="https://lockdrop.astroport.fi/"
        textTransform="uppercase"
        isExternal
      >
        {t("livebanner-title")}
      </Link>
      <Link
        href="https://lockdrop.astroport.fi/"
        textTransform="uppercase"
        isExternal
      >
        {t("livebanner-title")}
      </Link>
      <Link
        href="https://lockdrop.astroport.fi/"
        textTransform="uppercase"
        isExternal
      >
        {t("livebanner-title")}
      </Link>
      <Link
        href="https://lockdrop.astroport.fi/"
        textTransform="uppercase"
        isExternal
      >
        {t("livebanner-title")}
      </Link>
    </HStack>
  );
};

export default LiveBanner;
